name: Secure CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Dependency Security Scan
        run: |
          pip install pip-audit
          pip-audit

      - name: Secret Detection
        uses: gitleaks/gitleaks-action@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Run application test
        run: python -m py_compile app.py

      - name: Build Docker Image
        run: docker build -t secure-cicd-lab:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "secure-cicd-lab:latest"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"